'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';

export default function TermsOfUse() {
  const [lang, setLang] = useState<'ar' | 'en'>('ar');

  useEffect(() => {
    const savedLang = (localStorage.getItem('seerk_global_lang') as 'ar' | 'en') || 'ar';
    setLang(savedLang);
    if (typeof window !== 'undefined') {
      document.title = savedLang === 'ar' ? 'إنجازيا | شروط الاستخدام (السوق السعودي)' : 'Enjazya | Terms of Use (Saudi Market)';
    }
  }, []);

  const t = {
    ar: {
      back: '← عودة للمنصة',
      title: 'شروط الاستخدام ⚖️',
      lastUpdate: 'تاريخ آخر تحديث: ',
      sections: [
        {
          title: '1. مقدمة',
          content: 'أهلاً بكم في منصة "إنجازيا برو ماكس للحلول الرقمية". باستخدامك لأدواتنا وحاسباتنا المخصصة لقطاع التجارة الإلكترونية، فإنك توافق على الالتزام بشروط الاستخدام الماثلة. تُعد هذه الشروط عقداً ملزماً بينك وبين إدارة المنصة.'
        },
        {
          title: '2. نطاق الخدمات',
          content: 'توفر إنجازيا برو ماكس مجموعة من الأدوات التحليلية والمالية والتسويقية المصممة لدعم المتاجر الإلكترونية (سلة، زد، وغيرها). جميع النتائج والأرقام المستخرجة من حاسباتنا (مثل حاسبة الأرباح، الإقرار الضريبي، رسوم بوابات الدفع) هي تقديرية ومبنية على المدخلات التي يوفرها المستخدم، ولا تُغني عن الاستشارة المالية والمحاسبية المعتمدة.'
        },
        {
          title: '3. التراخيص والاشتراكات',
          points: [
            'الاشتراكات في باقات (Pro) تمنحك ترخيصاً شخصياً أو تجارياً غير قابل للتحويل لاستخدام الأدوات.',
            'يُمنع منعاً باتاً مشاركة مفتاح الترخيص الخاص بك مع أطراف أخرى أو إعادة بيع الخدمات المستخرجة من المنصة بصورة تجارية منافسة.'
          ]
        },
        {
          title: '4. إخلاء المسؤولية',
          content: 'نبذل قصارى جهدنا لضمان دقة العمليات الحسابية وتوافقها مع أنظمة السوق المحلي وهيئة الزكاة والضريبة والجمارك (ZATCA)، إلا أن إنجازيا برو ماكس لا تتحمل أي مسؤولية قانونية عن أي خسائر مالية أو أضرار مباشرة أو غير مباشرة قد تنتج عن قرارات تجارية اتُخذت بناءً على مخرجات المنصة.'
        },
        {
          title: '5. القانون المطبق',
          content: 'تخضع هذه الشروط وتُفسر وفقاً للأنظمة والقوانين المعمول بها في المملكة العربية السعودية.'
        }
      ]
    },
    en: {
      back: '→ Back to Hub',
      title: 'Terms of Use ⚖️',
      lastUpdate: 'Last Updated: ',
      sections: [
        {
          title: '1. Introduction',
          content: 'Welcome to "Enjazya Pro Max Digital Solutions". By using our tools and calculators tailored for the e-commerce sector, you agree to comply with these terms of use. These terms constitute a binding contract between you and the platform management.'
        },
        {
          title: '2. Scope of Services',
          content: 'Enjazya Pro Max provides a set of analytical, financial, and marketing tools designed to support e-commerce stores (Salla, Zid, etc.). All results and figures generated by our calculators (such as profit calculator, tax return, payment gateway fees) are estimations based on user inputs and do not replace certified financial and accounting consultation.'
        },
        {
          title: '3. Licenses & Subscriptions',
          points: [
            'Subscriptions to Pro plans grant you a personal or commercial non-transferable license to use the tools.',
            'It is strictly prohibited to share your license key with third parties or resell services extracted from the platform in a competing commercial manner.'
          ]
        },
        {
          title: '4. Disclaimer',
          content: 'We make every effort to ensure the accuracy of calculations and compliance with local market regulations and ZATCA guidelines; however, Enjazya Pro Max assumes no legal liability for any financial losses or direct/indirect damages resulting from business decisions made based on platform outputs.'
        },
        {
          title: '5. Governing Law',
          content: 'These terms are governed by and construed in accordance with the laws and regulations in force in the Kingdom of Saudi Arabia.'
        }
      ]
    }
  };

  const text = t[lang];

  return (
    <div style={{ direction: lang === 'ar' ? 'rtl' : 'ltr', fontFamily: lang === 'ar' ? "'Tajawal', sans-serif" : "'Inter', sans-serif", backgroundColor: '#f8fafc', minHeight: '100vh', padding: '40px 20px', textAlign: lang === 'ar' ? 'right' : 'left' }}>
      <div style={{ maxWidth: '800px', margin: '0 auto', background: '#fff', padding: '40px', borderRadius: '16px', boxShadow: '0 4px 20px rgba(0,0,0,0.03)', border: '1px solid #e2e8f0' }}>
        
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #f1f5f9', paddingBottom: '20px', marginBottom: '30px', flexWrap: 'wrap', gap: '15px', flexDirection: lang === 'ar' ? 'row' : 'row-reverse' }}>
          <h1 style={{ fontSize: '28px', fontWeight: 900, color: '#0f172a', margin: 0 }}>{text.title}</h1>
          <Link href="/hub/sa" style={{ background: '#f1f5f9', color: '#334155', padding: '8px 16px', borderRadius: '8px', textDecoration: 'none', fontWeight: 700, fontSize: '14px' }}>{text.back}</Link>
        </div>

        <div style={{ color: '#475569', lineHeight: '1.8', fontSize: '15px' }}>
          <p style={{ fontWeight: 700, marginBottom: '20px' }}>{text.lastUpdate}{new Date().toLocaleDateString(lang === 'ar' ? 'ar-SA' : 'en-US')}</p>
          
          {text.sections.map((section, idx) => (
            <div key={idx}>
              <h2 style={{ color: '#047857', fontSize: '20px', fontWeight: 800, marginTop: '30px' }}>{section.title}</h2>
              {section.content && <p>{section.content}</p>}
              {section.points && (
                <ul style={{ [lang === 'ar' ? 'paddingRight' : 'paddingLeft']: '20px' }}>
                  {section.points.map((pt, i) => (
                    <li key={i} style={{ marginBottom: '10px' }}>{pt}</li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
